import './js/authFireBase.js';
import './js/openModalWindow.js';
import './js/my-library-watched-queue/my-library-watched-queue';
import './js/dark-mode';
import { spinnerStart, spinnerStop } from './js/loader';
spinnerStart();
setTimeout(spinnerStop, 1000);
import './js/scroll_to_top';
import './js/movie_modal-library.js';
import './js/openModalWindow.js';
import './js/canvas-header.js';
